In [6]:
import cv2
import numpy as np

def nothing(x):
    pass

# 이미지 로드
cap = cv2.VideoCapture(0)

cv2.namedWindow('Color Detector', cv2.WINDOW_NORMAL)

# Trackbar를 생성하여 'Lower'와 'Upper' 범위 설정
cv2.createTrackbar('Low H', 'Color Detector', 0, 179, nothing)
cv2.createTrackbar('High H', 'Color Detector', 100, 179, nothing)
cv2.createTrackbar('Low S', 'Color Detector', 0, 250, nothing)
cv2.createTrackbar('High S', 'Color Detector', 200, 250, nothing)
cv2.createTrackbar('Low V', 'Color Detector', 0, 250, nothing)
cv2.createTrackbar('High V', 'Color Detector', 200, 250, nothing)


while True:
    # 복사본 이미지 생성
    _, frame = cap.read()

    # 트랙바에서 현재 값 얻기
    low_h = cv2.getTrackbarPos('Low H', 'Color Detector')
    high_h = cv2.getTrackbarPos('High H', 'Color Detector')
    low_s = cv2.getTrackbarPos('Low S', 'Color Detector')
    high_s = cv2.getTrackbarPos('High S', 'Color Detector')
    low_v = cv2.getTrackbarPos('Low V', 'Color Detector')
    high_v = cv2.getTrackbarPos('High V', 'Color Detector')

    # HSV 색상 공간으로 이미지 변환
    img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    # HSV에서의 lower/upper 임계값
    lower_color = np.array([low_h, low_s, low_v])
    upper_color= np.array([high_h, high_s, high_v])
    # print(lower_color, upper_color)

    # lower/upper 임계값을 이용하여 마스크 생성
    mask = cv2.inRange(img_hsv, lower_color, upper_color)

    kernel = np.ones((5, 5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:
        max_contour = max(contours, key=cv2.contourArea)
        print(max_contour) 
        if cv2.contourArea(max_contour)>1000:
            cv2.drawContours(frame, [max_contour], -1, (0,255,0),2)
        
    # 원본 이미지에 마스크 적용
    result = cv2.bitwise_and(frame, frame, mask=mask)
    # 결과 표시
    cv2.imshow('Original Image', frame)
    cv2.imshow('Color Detector', result)


    # 키 입력 대기 (ESC를 누르면 종료)
    
    if cv2.waitKey(10) & 0xff== ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

[[[  0   0]]

 [[  0  85]]

 [[  9  85]]

 [[ 10  86]]

 [[ 15  86]]

 [[ 17  88]]

 [[ 21  88]]

 [[ 22  87]]

 [[ 27  87]]

 [[ 28  86]]

 [[ 30  86]]

 [[ 32  84]]

 [[ 37  84]]

 [[ 38  85]]

 [[ 43  85]]

 [[ 44  86]]

 [[ 46  86]]

 [[ 48  88]]

 [[ 54  88]]

 [[ 55  89]]

 [[ 66  89]]

 [[ 67  88]]

 [[ 76  88]]

 [[ 76  74]]

 [[ 77  73]]

 [[ 77  71]]

 [[ 78  70]]

 [[ 82  70]]

 [[ 82  64]]

 [[ 83  63]]

 [[ 84  63]]

 [[ 84  62]]

 [[ 85  61]]

 [[ 85  60]]

 [[ 86  59]]

 [[ 86  50]]

 [[ 87  49]]

 [[ 92  49]]

 [[ 93  48]]

 [[ 97  48]]

 [[ 98  49]]

 [[ 98  51]]

 [[ 99  51]]

 [[100  52]]

 [[100  56]]

 [[ 98  58]]

 [[ 98  61]]

 [[ 97  62]]

 [[ 93  62]]

 [[ 93  64]]

 [[ 92  65]]

 [[ 92  66]]

 [[ 91  67]]

 [[ 88  67]]

 [[ 88  68]]

 [[ 87  69]]

 [[ 85  69]]

 [[ 85  81]]

 [[ 86  82]]

 [[ 86  92]]

 [[ 87  93]]

 [[ 87  94]]

 [[ 88  95]]

 [[ 89  95]]

 [[ 90  96]]

 [[ 90 101]]

 [[ 89 102]]

 [[ 87 102]]

 [[ 87 103]]

 [[ 86 104]]

 [[ 86 105]]

 [[ 85

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:230: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'


: 