In [18]:
import numpy as np
#
# 3x3x3 배열 생성
array = np.arange(27).reshape((3, 3, 3))

# 1 첫 번째 "층" 선택
print(array[0, :,:])

# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]]

#2. 배열에서 마지막 "층"을 선택하세요.
array2 = np.arange(18,27).reshape(3,3)
print(array2)
print(array1[2,:])
# [[18 19 20]
#  [21 22 23]
#  [24 25 26]]

#3. 두 번째 "층"의 첫 번째 행 선택
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]]

array3 = np.arange(9).reshape(3,3)
print(array3)
print(array3[1,0])

#4. 첫 번째 "층"의 첫 번째 열 선택
# [0 3 6]
print(array3[:,0])

#5. 두 번째 "층"의 두 번째 열 선택
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]]
print(array3[:,1])


#6. 모든 "층"의 중앙 요소 선택
# [ 4 13 22]


#7. 각 "층"의 마지막 행 선택
# [[ 6  7  8]
#  [15 16 17]
#  [24 25 26]]
print(array3[:,2])

#8. 각 "층"의 첫 번째 열 선택
# [[ 0  3  6]
#  [ 9 12 15]
#  [18 21 24]]

#9. 두 번째 "층"의 중앙 2x2 배열 선택
# [[13 14]
#  [16 17]]


#10. 첫 번째와 세 번째 "층"의 모든 요소 선택
# [[[ 0  1  2]
#   [ 3  4  5]
#   [ 6  7  8]]

#  [[18 19 20]
#   [21 22 23]
#   [24 25 26]]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
[6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
3
[0 3 6]
[1 4 7]
[2 5 8]
